export const studioProjects = [
  { slug:'arcanian', route:'#/arcanian', kind:'game', status:'development', theme:'arcanian' },
  { slug:'devaneios', route:'#/devaneios', kind:'book', status:'available', theme:'arcanian' },
  { slug:'menos-um', route:null, kind:'book', status:'announced', theme:'arcanian' },
  { slug:'tormenta', route:null, kind:'comic', status:'announced', theme:'arcanian' },
  { slug:'a-ultima-danca', route:null, kind:'book', status:'announced', theme:'arcanian' }
];

export const studioCopy = {
  pt: {
    nav:{projects:'Projetos',arcanian:'Arcanian',news:'Notícias',about:'Sobre',contact:'Contato',language:'Idioma',accessibility:'Acessibilidade'},
    hero:{kicker:'ESTÚDIO INDEPENDENTE BRASILEIRO',title:'TWO EYES ON YOU',line:'Histórias assumem formas diferentes.',media:'Games / Books / Comics / Worlds',featured:'Agora: ARCANIAN',featuredCta:'Entrar em Arcanian'},
    featured:{kicker:'PROPRIEDADE EM DESTAQUE',title:'ARCANIAN',label:'Uma propriedade original da Two Eyes On You.',line:'Algumas investigações deveriam permanecer incompletas.',formats:'GAME · BOOKS · COMICS',cta:'EXPLORAR ARCANIAN'},
    work:{kicker:'OUR WORK',title:'Obras, não vitrines.',text:'Cada projeto recebe a forma que a história pede.',game:'Jogo / Universo',book:'Livro · Episódio I',announced:'ANUNCIADOS',announcedText:'Outras histórias estão sendo escritas.'},
    now:{kicker:'AGORA',title:'O que está acontecendo.',game:'ARCANIAN',gameStatus:'Em desenvolvimento',book:'DEVANEIOS',bookStatus:'Disponível',firstLook:'ARCANIAN — VISLUMBRE DE GAMEPLAY',firstLookStatus:'Dezembro de 2026'},
    newsroom:{kicker:'NEWSROOM',title:'Últimas notícias.',all:'VER TODAS'},
    intro:{kicker:'TWO EYES ON YOU',title:'Uma história não precisa existir em um único formato.',text:'Estúdio independente brasileiro criando propriedades intelectuais originais por meio de jogos, livros, quadrinhos e experiências digitais.',cta:'SOBRE O ESTÚDIO'},
    projects:{kicker:'PROJETOS',title:'Cada obra entra em cena do seu jeito.',text:'Arcanian é a propriedade central atual. A estrutura está preparada para novas histórias que não precisem pertencer ao mesmo universo.',open:'ABRIR PROJETO',arcanianLine:'Investigação, cotidiano e acontecimentos impossíveis ocupando o mesmo espaço.',devaneiosLine:'O primeiro episódio publicado de Arcanian.',announced:'ANUNCIADOS',announcedText:'Títulos revelados, ainda não apresentados como lançamentos disponíveis.'},
    arcanian:{kicker:'UMA PROPRIEDADE ORIGINAL',title:'ARCANIAN',line:'Uma investigação pequena demais para justificar o que veio depois.',intro:'Jogo, livros e quadrinhos compartilham um universo, mas não repetem a mesma história da mesma forma.',game:'JOGO',gameTitle:'A investigação precisa continuar.',gameText:'Uma aventura narrativa de ação com investigação, suspense, terror psicológico e lugares cotidianos atravessados pelo impossível.',book:'LIVRO',bookTitle:'Devaneios.',bookText:'O Episódio I acompanha o caso que traz Ikarius de volta ao legado de Mountevoir.',world:'MUNDO',worldTitle:'Lugares antes de mitologias.',worldText:'Bairros, cidades, instituições, ruas e casas continuam existindo quando o extraordinário aparece.',media:'MÍDIA',mediaTitle:'Imagem, movimento e desenvolvimento.',archive:'ARQUIVO',archiveTitle:'O universo tem memória.',archiveText:'Personagens, famílias, organizações, eventos, lugares e documentos organizados como arquivo investigativo.',archiveCta:'ENTRAR NO ARQUIVO',platforms:'PLATAFORMAS COMUNICADAS'},
    world:{kicker:'ARCANIAN / MUNDO',title:'O extraordinário aparece dentro da rotina.',text:'Os lugares de Arcanian são vividos antes de serem misteriosos. Arquitetura, circulação e cotidiano importam tanto quanto a ameaça.'},
    books:{kicker:'ARCANIAN / LIVROS',title:'Histórias longas. Consequências mais longas ainda.',text:'Devaneios abre a publicação do universo. Outros títulos já anunciados ampliam perspectivas sem serem tratados como lançamentos disponíveis.'},
    about:{kicker:'SOBRE',title:'Two Eyes On You.',line:'Independent entertainment studio from Brazil.',formats:'Games. Books. Comics. Worlds.',text:'A Two Eyes On You desenvolve propriedades intelectuais e histórias por diferentes mídias. Arcanian começou como uma ideia e cresceu para ocupar jogo, literatura e quadrinhos — sem exigir que cada formato conte exatamente a mesma coisa.'},
    contact:{kicker:'CONTATO',title:'Fale com a Two Eyes On You.',text:'Imprensa, negócios, parcerias, suporte ou contato geral.',name:'Nome',email:'E-mail',subject:'Assunto',message:'Mensagem',send:'ENVIAR POR E-MAIL',topics:['Business','Press','Partnerships','Support','General'],note:'O formulário abre seu cliente de e-mail; nenhum dado é enviado para um servidor deste site.'},
    press:{kicker:'PRESS KIT',title:'Two Eyes On You — Press.',short:'Estúdio independente brasileiro de entretenimento e tecnologia criando jogos, livros, quadrinhos e propriedades intelectuais originais.',long:'A Two Eyes On You desenvolve histórias em diferentes formatos, tratando cada mídia como parte de um universo criativo em vez de departamentos isolados. Arcanian é sua principal propriedade atual.',assets:'ATIVOS',company:'INFORMAÇÕES',contact:'CONTATO DE IMPRENSA'},
    accessibility:{kicker:'ACESSIBILIDADE',title:'Controles discretos. Navegação real.',text:'O site oferece ajuste de texto, alto contraste, redução de movimento, foco visível e navegação por teclado.',textSize:'Tamanho do texto',contrast:'Alto contraste',motion:'Reduzir movimento',smaller:'Reduzir',larger:'Aumentar',reset:'Restaurar',on:'Ativado',off:'Desativado',close:'Fechar'},
    footer:{projects:'Projects',news:'News',about:'About',contact:'Contact',privacy:'Privacy',terms:'Terms',accessibility:'Accessibility',press:'Press',rights:'© Two Eyes On You. Todos os direitos reservados.',ip:'ARCANIAN e seus nomes, personagens, logotipos e propriedades relacionadas são propriedades intelectuais da Two Eyes On You e/ou de seus respectivos titulares, quando aplicável.',thirdParty:'Marcas de terceiros pertencem aos seus respectivos proprietários.'},
    notFound:{title:'NADA ESTÁ OLHANDO DE VOLTA.',text:'A página que você procurou não está aqui.',cta:'VOLTAR AO INÍCIO'}
  },
  en: {
    nav:{projects:'Projects',arcanian:'Arcanian',news:'News',about:'About',contact:'Contact',language:'Language',accessibility:'Accessibility'},
    hero:{kicker:'INDEPENDENT STUDIO FROM BRAZIL',title:'TWO EYES ON YOU',line:'Stories take different forms.',media:'Games / Books / Comics / Worlds',featured:'Now: ARCANIAN',featuredCta:'Enter Arcanian'},
    featured:{kicker:'FEATURED PROPERTY',title:'ARCANIAN',label:'An original property by Two Eyes On You.',line:'Some investigations should remain unfinished.',formats:'GAME · BOOKS · COMICS',cta:'EXPLORE ARCANIAN'},
    work:{kicker:'OUR WORK',title:'Works, not storefronts.',text:'Each project takes the form its story needs.',game:'Game / Universe',book:'Book · Episode I',announced:'ANNOUNCED',announcedText:'Other stories are being written.'},
    now:{kicker:'NOW',title:'What is happening.',game:'ARCANIAN',gameStatus:'In development',book:'DEVANEIOS',bookStatus:'Available',firstLook:'ARCANIAN — GAMEPLAY FIRST LOOK',firstLookStatus:'December 2026'},
    newsroom:{kicker:'NEWSROOM',title:'Latest news.',all:'VIEW ALL'},
    intro:{kicker:'TWO EYES ON YOU',title:'A story does not have to exist in only one format.',text:'An independent Brazilian studio creating original intellectual properties through games, books, comics and digital experiences.',cta:'ABOUT THE STUDIO'},
    projects:{kicker:'PROJECTS',title:'Every work enters the frame differently.',text:'Arcanian is the current central property. The structure is ready for new stories that do not need to belong to the same universe.',open:'OPEN PROJECT',arcanianLine:'Investigation, everyday life and impossible events occupying the same space.',devaneiosLine:'The first published episode of Arcanian.',announced:'ANNOUNCED',announcedText:'Revealed titles, not presented as currently available releases.'},
    arcanian:{kicker:'AN ORIGINAL PROPERTY',title:'ARCANIAN',line:'An investigation too small to justify what came after.',intro:'Game, books and comics share a universe without retelling the same story in the same way.',game:'GAME',gameTitle:'The investigation must continue.',gameText:'A narrative action adventure built around investigation, suspense, psychological horror and ordinary places crossed by the impossible.',book:'BOOK',bookTitle:'Devaneios.',bookText:'Episode I follows the case that brings Ikarius back to the Mountevoir legacy.',world:'WORLD',worldTitle:'Places before mythologies.',worldText:'Neighborhoods, cities, institutions, streets and homes keep functioning when the extraordinary appears.',media:'MEDIA',mediaTitle:'Image, movement and development.',archive:'ARCHIVE',archiveTitle:'The universe has a memory.',archiveText:'Characters, families, organizations, events, places and documents arranged as an investigative archive.',archiveCta:'ENTER THE ARCHIVE',platforms:'COMMUNICATED PLATFORMS'},
    world:{kicker:'ARCANIAN / WORLD',title:'The extraordinary appears inside routine.',text:'Arcanian places are lived in before they are mysterious. Architecture, circulation and ordinary life matter as much as the threat.'},
    books:{kicker:'ARCANIAN / BOOKS',title:'Long stories. Longer consequences.',text:'Devaneios opens the published side of the universe. Other announced titles expand perspectives without being presented as available releases.'},
    about:{kicker:'ABOUT',title:'Two Eyes On You.',line:'Independent entertainment studio from Brazil.',formats:'Games. Books. Comics. Worlds.',text:'Two Eyes On You develops intellectual properties and stories across different media. Arcanian began as an idea and grew into games, literature and comics — without requiring every format to tell exactly the same thing.'},
    contact:{kicker:'CONTACT',title:'Talk to Two Eyes On You.',text:'Press, business, partnerships, support or general contact.',name:'Name',email:'Email',subject:'Subject',message:'Message',send:'SEND BY EMAIL',topics:['Business','Press','Partnerships','Support','General'],note:'The form opens your email client; no data is sent to a server owned by this site.'},
    press:{kicker:'PRESS KIT',title:'Two Eyes On You — Press.',short:'Independent Brazilian entertainment and technology studio creating games, books, comics and original intellectual properties.',long:'Two Eyes On You develops stories in different formats, treating each medium as part of a creative universe rather than isolated departments. Arcanian is its main current property.',assets:'ASSETS',company:'INFORMATION',contact:'PRESS CONTACT'},
    accessibility:{kicker:'ACCESSIBILITY',title:'Discrete controls. Real navigation.',text:'The site offers text sizing, high contrast, reduced motion, visible focus and keyboard navigation.',textSize:'Text size',contrast:'High contrast',motion:'Reduce motion',smaller:'Smaller',larger:'Larger',reset:'Reset',on:'On',off:'Off',close:'Close'},
    footer:{projects:'Projects',news:'News',about:'About',contact:'Contact',privacy:'Privacy',terms:'Terms',accessibility:'Accessibility',press:'Press',rights:'© Two Eyes On You. All rights reserved.',ip:'ARCANIAN and related names, characters, logos and properties are intellectual properties of Two Eyes On You and/or their respective rights holders where applicable.',thirdParty:'Third-party trademarks belong to their respective owners.'},
    notFound:{title:'NOTHING IS LOOKING BACK.',text:'The page you were looking for is not here.',cta:'RETURN HOME'}
  },
  es: {
    nav:{projects:'Proyectos',arcanian:'Arcanian',news:'Noticias',about:'Sobre',contact:'Contacto',language:'Idioma',accessibility:'Accesibilidad'},
    hero:{kicker:'ESTUDIO INDEPENDIENTE DE BRASIL',title:'TWO EYES ON YOU',line:'Las historias toman formas diferentes.',media:'Juegos / Libros / Cómics / Mundos',featured:'Ahora: ARCANIAN',featuredCta:'Entrar en Arcanian'},
    featured:{kicker:'PROPIEDAD DESTACADA',title:'ARCANIAN',label:'Una propiedad original de Two Eyes On You.',line:'Algunas investigaciones deberían quedar incompletas.',formats:'JUEGO · LIBROS · CÓMICS',cta:'EXPLORAR ARCANIAN'},
    work:{kicker:'NUESTRO TRABAJO',title:'Obras, no escaparates.',text:'Cada proyecto adopta la forma que necesita su historia.',game:'Juego / Universo',book:'Libro · Episodio I',announced:'ANUNCIADOS',announcedText:'Otras historias se están escribiendo.'},
    now:{kicker:'AHORA',title:'Lo que está ocurriendo.',game:'ARCANIAN',gameStatus:'En desarrollo',book:'DEVANEIOS',bookStatus:'Disponible',firstLook:'ARCANIAN — ADELANTO DE GAMEPLAY',firstLookStatus:'Diciembre de 2026'},
    newsroom:{kicker:'NEWSROOM',title:'Últimas noticias.',all:'VER TODAS'},
    intro:{kicker:'TWO EYES ON YOU',title:'Una historia no tiene que existir en un solo formato.',text:'Estudio independiente brasileño que crea propiedades intelectuales originales mediante juegos, libros, cómics y experiencias digitales.',cta:'SOBRE EL ESTUDIO'},
    projects:{kicker:'PROYECTOS',title:'Cada obra entra en escena de forma distinta.',text:'Arcanian es la propiedad central actual. La estructura está lista para nuevas historias que no necesiten pertenecer al mismo universo.',open:'ABRIR PROYECTO',arcanianLine:'Investigación, vida cotidiana y hechos imposibles ocupando el mismo espacio.',devaneiosLine:'El primer episodio publicado de Arcanian.',announced:'ANUNCIADOS',announcedText:'Títulos revelados, todavía no presentados como lanzamientos disponibles.'},
    arcanian:{kicker:'UNA PROPIEDAD ORIGINAL',title:'ARCANIAN',line:'Una investigación demasiado pequeña para justificar lo que vino después.',intro:'Juego, libros y cómics comparten un universo sin repetir la misma historia de la misma forma.',game:'JUEGO',gameTitle:'La investigación debe continuar.',gameText:'Una aventura narrativa de acción con investigación, suspense, terror psicológico y lugares cotidianos atravesados por lo imposible.',book:'LIBRO',bookTitle:'Devaneios.',bookText:'El Episodio I sigue el caso que devuelve a Ikarius al legado Mountevoir.',world:'MUNDO',worldTitle:'Lugares antes que mitologías.',worldText:'Barrios, ciudades, instituciones, calles y casas siguen funcionando cuando aparece lo extraordinario.',media:'MEDIA',mediaTitle:'Imagen, movimiento y desarrollo.',archive:'ARCHIVO',archiveTitle:'El universo tiene memoria.',archiveText:'Personajes, familias, organizaciones, eventos, lugares y documentos organizados como un archivo investigativo.',archiveCta:'ENTRAR AL ARCHIVO',platforms:'PLATAFORMAS COMUNICADAS'},
    world:{kicker:'ARCANIAN / MUNDO',title:'Lo extraordinario aparece dentro de la rutina.',text:'Los lugares de Arcanian se viven antes de ser misteriosos. Arquitectura, circulación y vida cotidiana importan tanto como la amenaza.'},
    books:{kicker:'ARCANIAN / LIBROS',title:'Historias largas. Consecuencias aún más largas.',text:'Devaneios abre la publicación del universo. Otros títulos anunciados amplían perspectivas sin presentarse como lanzamientos disponibles.'},
    about:{kicker:'SOBRE',title:'Two Eyes On You.',line:'Independent entertainment studio from Brazil.',formats:'Games. Books. Comics. Worlds.',text:'Two Eyes On You desarrolla propiedades intelectuales e historias en distintos medios. Arcanian comenzó como una idea y creció hacia el juego, la literatura y los cómics sin exigir que cada formato cuente exactamente lo mismo.'},
    contact:{kicker:'CONTACTO',title:'Habla con Two Eyes On You.',text:'Prensa, negocios, alianzas, soporte o contacto general.',name:'Nombre',email:'Email',subject:'Asunto',message:'Mensaje',send:'ENVIAR POR EMAIL',topics:['Business','Press','Partnerships','Support','General'],note:'El formulario abre tu cliente de correo; ningún dato se envía a un servidor de este sitio.'},
    press:{kicker:'PRESS KIT',title:'Two Eyes On You — Press.',short:'Estudio independiente brasileño de entretenimiento y tecnología que crea juegos, libros, cómics y propiedades intelectuales originales.',long:'Two Eyes On You desarrolla historias en distintos formatos, tratando cada medio como parte de universos creativos y no como departamentos aislados. Arcanian es su principal propiedad actual.',assets:'ACTIVOS',company:'INFORMACIÓN',contact:'CONTACTO DE PRENSA'},
    accessibility:{kicker:'ACCESIBILIDAD',title:'Controles discretos. Navegación real.',text:'El sitio ofrece ajuste de texto, alto contraste, reducción de movimiento, foco visible y navegación por teclado.',textSize:'Tamaño del texto',contrast:'Alto contraste',motion:'Reducir movimiento',smaller:'Reducir',larger:'Aumentar',reset:'Restaurar',on:'Activado',off:'Desactivado',close:'Cerrar'},
    footer:{projects:'Projects',news:'News',about:'About',contact:'Contact',privacy:'Privacy',terms:'Terms',accessibility:'Accessibility',press:'Press',rights:'© Two Eyes On You. Todos los derechos reservados.',ip:'ARCANIAN y sus nombres, personajes, logotipos y propiedades relacionadas son propiedades intelectuales de Two Eyes On You y/o de sus respectivos titulares cuando corresponda.',thirdParty:'Las marcas de terceros pertenecen a sus respectivos propietarios.'},
    notFound:{title:'NADA ESTÁ MIRANDO DE VUELTA.',text:'La página que buscabas no está aquí.',cta:'VOLVER AL INICIO'}
  },
  it: {
    nav:{projects:'Progetti',arcanian:'Arcanian',news:'Notizie',about:'Chi siamo',contact:'Contatti',language:'Lingua',accessibility:'Accessibilità'},
    hero:{kicker:'STUDIO INDIPENDENTE BRASILIANO',title:'TWO EYES ON YOU',line:'Le storie assumono forme diverse.',media:'Giochi / Libri / Fumetti / Mondi',featured:'Ora: ARCANIAN',featuredCta:'Entra in Arcanian'},
    featured:{kicker:'PROPRIETÀ IN EVIDENZA',title:'ARCANIAN',label:'Una proprietà originale di Two Eyes On You.',line:'Alcune indagini dovrebbero restare incomplete.',formats:'GIOCO · LIBRI · FUMETTI',cta:'ESPLORA ARCANIAN'},
    work:{kicker:'OUR WORK',title:'Opere, non vetrine.',text:'Ogni progetto assume la forma richiesta dalla storia.',game:'Gioco / Universo',book:'Libro · Episodio I',announced:'ANNUNCIATI',announcedText:'Altre storie sono in scrittura.'},
    now:{kicker:'ORA',title:'Cosa sta succedendo.',game:'ARCANIAN',gameStatus:'In sviluppo',book:'DEVANEIOS',bookStatus:'Disponibile',firstLook:'ARCANIAN — PRIMO SGUARDO AL GAMEPLAY',firstLookStatus:'Dicembre 2026'},
    newsroom:{kicker:'NEWSROOM',title:'Ultime notizie.',all:'VEDI TUTTE'},
    intro:{kicker:'TWO EYES ON YOU',title:'Una storia non deve esistere in un solo formato.',text:'Studio brasiliano indipendente che crea proprietà intellettuali originali attraverso giochi, libri, fumetti ed esperienze digitali.',cta:'LO STUDIO'},
    projects:{kicker:'PROGETTI',title:'Ogni opera entra in scena a modo suo.',text:'Arcanian è la proprietà centrale attuale. La struttura è pronta per nuove storie che non devono appartenere allo stesso universo.',open:'APRI PROGETTO',arcanianLine:'Indagine, vita quotidiana ed eventi impossibili nello stesso spazio.',devaneiosLine:'Il primo episodio pubblicato di Arcanian.',announced:'ANNUNCIATI',announcedText:'Titoli rivelati, non ancora presentati come uscite disponibili.'},
    arcanian:{kicker:'UNA PROPRIETÀ ORIGINALE',title:'ARCANIAN',line:'Un’indagine troppo piccola per giustificare ciò che è venuto dopo.',intro:'Gioco, libri e fumetti condividono un universo senza raccontare la stessa storia nello stesso modo.',game:'GIOCO',gameTitle:'L’indagine deve continuare.',gameText:'Un’avventura narrativa d’azione con indagine, suspense, horror psicologico e luoghi quotidiani attraversati dall’impossibile.',book:'LIBRO',bookTitle:'Devaneios.',bookText:'L’Episodio I segue il caso che riporta Ikarius all’eredità Mountevoir.',world:'MONDO',worldTitle:'Luoghi prima delle mitologie.',worldText:'Quartieri, città, istituzioni, strade e case continuano a funzionare quando appare lo straordinario.',media:'MEDIA',mediaTitle:'Immagine, movimento e sviluppo.',archive:'ARCHIVIO',archiveTitle:'L’universo ha una memoria.',archiveText:'Personaggi, famiglie, organizzazioni, eventi, luoghi e documenti organizzati come archivio investigativo.',archiveCta:'ENTRA NELL’ARCHIVIO',platforms:'PIATTAFORME COMUNICATE'},
    world:{kicker:'ARCANIAN / MONDO',title:'Lo straordinario appare dentro la routine.',text:'I luoghi di Arcanian sono vissuti prima di essere misteriosi. Architettura, circolazione e quotidianità contano quanto la minaccia.'},
    books:{kicker:'ARCANIAN / LIBRI',title:'Storie lunghe. Conseguenze ancora più lunghe.',text:'Devaneios apre la pubblicazione dell’universo. Gli altri titoli annunciati ampliano le prospettive senza essere presentati come uscite disponibili.'},
    about:{kicker:'CHI SIAMO',title:'Two Eyes On You.',line:'Independent entertainment studio from Brazil.',formats:'Games. Books. Comics. Worlds.',text:'Two Eyes On You sviluppa proprietà intellettuali e storie attraverso media differenti. Arcanian è nato come idea ed è cresciuto tra gioco, letteratura e fumetto senza obbligare ogni formato a raccontare esattamente la stessa cosa.'},
    contact:{kicker:'CONTATTI',title:'Parla con Two Eyes On You.',text:'Stampa, business, partnership, supporto o contatto generale.',name:'Nome',email:'Email',subject:'Oggetto',message:'Messaggio',send:'INVIA VIA EMAIL',topics:['Business','Press','Partnerships','Support','General'],note:'Il modulo apre il client email; nessun dato viene inviato a un server di questo sito.'},
    press:{kicker:'PRESS KIT',title:'Two Eyes On You — Press.',short:'Studio brasiliano indipendente di intrattenimento e tecnologia che crea giochi, libri, fumetti e proprietà intellettuali originali.',long:'Two Eyes On You sviluppa storie in formati diversi, trattando ogni mezzo come parte di universi creativi e non come reparti isolati. Arcanian è la proprietà principale attuale.',assets:'ASSET',company:'INFORMAZIONI',contact:'CONTATTO STAMPA'},
    accessibility:{kicker:'ACCESSIBILITÀ',title:'Controlli discreti. Navigazione reale.',text:'Il sito offre regolazione del testo, alto contrasto, riduzione del movimento, focus visibile e navigazione da tastiera.',textSize:'Dimensione testo',contrast:'Alto contrasto',motion:'Riduci movimento',smaller:'Riduci',larger:'Aumenta',reset:'Ripristina',on:'Attivo',off:'Disattivo',close:'Chiudi'},
    footer:{projects:'Projects',news:'News',about:'About',contact:'Contact',privacy:'Privacy',terms:'Terms',accessibility:'Accessibility',press:'Press',rights:'© Two Eyes On You. Tutti i diritti riservati.',ip:'ARCANIAN e relativi nomi, personaggi, loghi e proprietà sono proprietà intellettuali di Two Eyes On You e/o dei rispettivi titolari, ove applicabile.',thirdParty:'I marchi di terzi appartengono ai rispettivi proprietari.'},
    notFound:{title:'NIENTE STA GUARDANDO INDIETRO.',text:'La pagina che cercavi non è qui.',cta:'TORNA ALLA HOME'}
  },
  ja: {
    nav:{projects:'プロジェクト',arcanian:'Arcanian',news:'ニュース',about:'概要',contact:'お問い合わせ',language:'言語',accessibility:'アクセシビリティ'},
    hero:{kicker:'ブラジルのインディペンデントスタジオ',title:'TWO EYES ON YOU',line:'物語は、形を変える。',media:'Games / Books / Comics / Worlds',featured:'現在: ARCANIAN',featuredCta:'Arcanianへ'},
    featured:{kicker:'注目プロパティ',title:'ARCANIAN',label:'Two Eyes On Youのオリジナルプロパティ。',line:'未完のままにすべき捜査もある。',formats:'GAME · BOOKS · COMICS',cta:'ARCANIANを探索'},
    work:{kicker:'OUR WORK',title:'商品棚ではなく、作品。',text:'物語が求める形を、それぞれのプロジェクトに。',game:'ゲーム / 世界',book:'書籍 · エピソードI',announced:'発表済み',announcedText:'別の物語も書かれています。'},
    now:{kicker:'NOW',title:'現在の動き。',game:'ARCANIAN',gameStatus:'開発中',book:'DEVANEIOS',bookStatus:'発売中',firstLook:'ARCANIAN — ゲームプレイ初公開',firstLookStatus:'2026年12月'},
    newsroom:{kicker:'NEWSROOM',title:'最新ニュース。',all:'すべて見る'},
    intro:{kicker:'TWO EYES ON YOU',title:'物語は、一つの形式だけに存在する必要はない。',text:'ゲーム、書籍、コミック、デジタル体験を通してオリジナルIPを生み出すブラジルのインディペンデントスタジオ。',cta:'スタジオについて'},
    projects:{kicker:'プロジェクト',title:'作品ごとに、登場の仕方が違う。',text:'現在の中心プロパティはArcanian。将来、同じ世界に属さない新しい物語も加えられる構造です。',open:'プロジェクトを開く',arcanianLine:'捜査、日常、そして不可能な出来事が同じ空間に存在する。',devaneiosLine:'Arcanianで最初に刊行されたエピソード。',announced:'発表済み',announcedText:'公開済みのタイトル。現在発売中の作品としては扱いません。'},
    arcanian:{kicker:'オリジナルプロパティ',title:'ARCANIAN',line:'その後に起きたことを説明するには、小さすぎた捜査。',intro:'ゲーム、書籍、コミックは同じ世界を共有しながら、同じ物語を同じ形では繰り返しません。',game:'ゲーム',gameTitle:'捜査は続けなければならない。',gameText:'捜査、サスペンス、心理的恐怖、そして日常の場所に入り込む不可能を描くナラティブアクション。',book:'書籍',bookTitle:'Devaneios.',bookText:'エピソードIはIkariusをMountevoirの遺産へ戻す事件を描きます。',world:'世界',worldTitle:'神話より先に、場所がある。',worldText:'異常が現れても、地区、都市、組織、通り、家は動き続けます。',media:'メディア',mediaTitle:'映像、動き、開発。',archive:'アーカイブ',archiveTitle:'世界には記憶がある。',archiveText:'人物、家族、組織、出来事、場所、文書を捜査資料のように整理します。',archiveCta:'アーカイブへ',platforms:'発表済みプラットフォーム'},
    world:{kicker:'ARCANIAN / WORLD',title:'非日常は、日常の中に現れる。',text:'Arcanianの場所は、謎である前に生活の場です。建築、移動、日常は脅威と同じくらい重要です。'},
    books:{kicker:'ARCANIAN / BOOKS',title:'長い物語。さらに長い結果。',text:'Devaneiosが刊行作品の入口です。ほかの発表済み作品は、発売中として扱わずに視点を広げます。'},
    about:{kicker:'ABOUT',title:'Two Eyes On You.',line:'Independent entertainment studio from Brazil.',formats:'Games. Books. Comics. Worlds.',text:'Two Eyes On Youは複数のメディアを通してIPと物語を開発します。Arcanianは一つのアイデアから始まり、ゲーム、文学、コミックへ広がりました。すべての形式が同じ内容を繰り返す必要はありません。'},
    contact:{kicker:'CONTACT',title:'Two Eyes On Youへのお問い合わせ。',text:'プレス、ビジネス、提携、サポート、一般のお問い合わせ。',name:'お名前',email:'メール',subject:'件名',message:'メッセージ',send:'メールで送る',topics:['Business','Press','Partnerships','Support','General'],note:'フォームはメールアプリを開きます。このサイトのサーバーへ情報は送信されません。'},
    press:{kicker:'PRESS KIT',title:'Two Eyes On You — Press.',short:'ゲーム、書籍、コミック、オリジナルIPを制作するブラジルのインディペンデント・エンターテインメント／テクノロジースタジオ。',long:'Two Eyes On Youは異なる形式で物語を開発し、各メディアを別部門ではなく一つの創造世界の一部として扱います。現在の主要プロパティはArcanianです。',assets:'アセット',company:'情報',contact:'プレス連絡先'},
    accessibility:{kicker:'ACCESSIBILITY',title:'控えめな操作。実用的なナビゲーション。',text:'文字サイズ、高コントラスト、動きの削減、見やすいフォーカス、キーボード操作に対応します。',textSize:'文字サイズ',contrast:'高コントラスト',motion:'動きを減らす',smaller:'小さく',larger:'大きく',reset:'リセット',on:'オン',off:'オフ',close:'閉じる'},
    footer:{projects:'Projects',news:'News',about:'About',contact:'Contact',privacy:'Privacy',terms:'Terms',accessibility:'Accessibility',press:'Press',rights:'© Two Eyes On You. All rights reserved.',ip:'ARCANIANおよび関連する名称、人物、ロゴ、プロパティは、適用される範囲でTwo Eyes On Youまたは各権利者の知的財産です。',thirdParty:'第三者の商標は各所有者に帰属します。'},
    notFound:{title:'NOTHING IS LOOKING BACK.',text:'探していたページはここにはありません。',cta:'ホームへ戻る'}
  }
};

export function getStudioCopy(lang='pt') {
  return studioCopy[lang] || studioCopy.en;
}
