import { workContentTranslations } from './fullTranslations.js';
import { createLocalizedWikiEntry } from './wikiLocalization.js';

export const languages = [
  { id: 'pt', label: 'Português', short: 'PT', html: 'pt-BR' },
  { id: 'en', label: 'English', short: 'EN', html: 'en' },
  { id: 'es', label: 'Español', short: 'ES', html: 'es' },
  { id: 'it', label: 'Italiano', short: 'IT', html: 'it' },
  { id: 'ja', label: '日本語', short: 'JA', html: 'ja' }
];

export const themes = [
  { id: 'night', key: 'night' },
  { id: 'sand', key: 'sand' },
  { id: 'blue', key: 'blue' }
];
const dictionaries = {
  pt: {
    nav: { home:'Início', projects:'Projetos', news:'Notícias', wiki:'Wiki', timeline:'Cronologia', media:'Mídia', studio:'Estúdio', documents:'Documentos', contact:'Contato', buy:'Comprar Devaneios' },
    routes: { '/':'Início', '/arcanian':'Projetos', '/wiki':'Wiki Arcanian', '/timeline':'Cronologia', '/news':'Notícias', '/media':'Mídia', '/about':'Estúdio', '/documentation':'Documentos', '/contact':'Contato', '/purchase':'Comprar Devaneios' },
    common: { explore:'Explorar', learn:'Saiba mais', viewAll:'Ver tudo', readMore:'Ler mais', back:'Voltar', search:'Pesquisar', close:'Fechar', buy:'Comprar', available:'Disponível', soon:'Em desenvolvimento', external:'Abre em outra plataforma', overview:'Visão geral', direction:'Direção', connections:'Conexões', noResults:'Nenhum resultado encontrado.', originalPt:'Conteúdo editorial disponível no original em português.' },
    settings: { title:'Preferências do site', description:'Ajuste idioma, identidade visual, leitura e acessibilidade. As escolhas ficam salvas neste navegador.', theme:'Tema', language:'Idioma', studio:'Ateliê Arcanian', night:'Arquivo Noturno', light:'Edição Museográfica', sand:'Códice Editorial', blue:'Terminal Analítico', open:'Escolher tema' },
    search: { title:'Busca rápida', placeholder:'Busque uma obra, notícia, pessoa ou página', navigation:'Navegação', work:'Projeto', wiki:'Wiki', document:'Documento' },
    home: {
      eyebrow:'Two Eyes On You Studios',
      title:'Histórias para ler, jogar e lembrar.',
      text:'A casa de Devaneios, Menos Um, Tormenta e do Jogo Arcanian.',
      primary:'Conheça nossos projetos', secondary:'Sobre o estúdio',
      featured:'Em destaque', latest:'Últimas notícias', projects:'Projetos do estúdio',
      projectsText:'Cada obra escolhe o formato que melhor serve à história. Arcanian conecta livros, HQ e jogo sem transformar tudo na mesma experiência.',
      studioTitle:'Uma obra não precisa terminar onde começou.',
      studioText:'A Two Eyes On You nasceu para criar projetos que atravessam formatos sem perder autoria. Primeiro definimos a cena, os personagens e a sensação. A tecnologia vem depois.',
      studioButton:'Conheça a Two Eyes On You'
    },
    projects: { eyebrow:'Arcanian em diferentes formas', title:'Projetos', text:'Quatro obras que entram no mesmo universo por conflitos e pontos de vista diferentes.', choose:'Escolha um projeto', intro:'Arcanian é o principal universo do estúdio. Cada título pode ser conhecido separadamente, mas todos compartilham consequências, personagens e ideias.' },
    work: { themes:'Pilares da obra', related:'Conheça também na wiki', wikiText:'Personagens, lugares e conceitos que ajudam a entender melhor esta obra.', wikiButton:'Abrir Wiki Arcanian' },
    wiki: { eyebrow:'Enciclopédia oficial', title:'Wiki Arcanian', text:'Personagens, lugares, organizações, acontecimentos e conceitos do universo.', categories:'Categorias', all:'Tudo', spoilers:'Exibir spoilers', protected:'Conteúdo com spoiler', open:'Abrir entrada', results:'entradas', source:'Fonte principal: Arcanian: Devaneios', original:'Texto original em português', back:'Voltar à wiki', related:'Entradas relacionadas', classification:'Categoria' },
    timeline: { eyebrow:'Universo Arcanian', title:'Cronologia', text:'Uma visão organizada dos acontecimentos conhecidos, com proteção para revelações importantes.', show:'Exibir spoilers', hide:'Ocultar spoilers', locked:'Evento protegido', lockedText:'Ative os spoilers para consultar este acontecimento.' },
    news: { eyebrow:'Two Eyes On You', title:'Notícias', text:'Lançamentos, produção, eventos e mudanças nos projetos do estúdio.' },
    media: { eyebrow:'Galeria do estúdio', title:'Mídia', text:'Imagens, vídeos, artes de desenvolvimento e materiais públicos.', video:'Vídeo em destaque', images:'Galeria' },
    studio: {
      eyebrow:'Two Eyes On You · desde 2018', title:'Two Eyes On You', text:'O estúdio desenvolve Arcanian em obras que não repetem a mesma história: Devaneios, Menos Um, Tormenta e o Jogo.',
      manifesto:'Nossa direção', manifestoTitle:'Cada obra precisa existir por um motivo próprio.',
      p1:'Devaneios usa a investigação e a voz interna de Ikarius. Menos Um se aproxima de Joel e Elisabeth. Tormenta transforma o passado em sequência visual. O Jogo entrega parte dessas decisões ao jogador.',
      p2:'Quando uma cena muda de formato, ela precisa ganhar alguma coisa: intimidade na prosa, tempo entre quadros, ação, cooperação ou controle. Caso contrário, não há razão para refazê-la.',
      areas:'O que fazemos', process:'Como trabalhamos', projects:'Em produção',
      processTitle:'Quem está na cena, o que está em risco e qual forma sustenta isso.',
      contact:'Parcerias, imprensa e licenciamento', contactTitle:'Converse diretamente com o estúdio.'
    },
    docs: { eyebrow:'Informações institucionais', title:'Documentos', text:'Políticas, termos de uso, licenças e diretrizes de marca.', summary:'Sumário', updated:'Atualizado em', legalOriginal:'A versão juridicamente válida deste documento está disponível em português.' },
    contact: { eyebrow:'Canal oficial', title:'Fale com a equipe', text:'Suporte, imprensa, parcerias, licenciamento e propriedade intelectual.', button:'Enviar e-mail', areas:['Suporte e falhas técnicas','Parcerias e colaborações','Imprensa e criadores','Licenciamento e direitos'] },
    purchase: {
      eyebrow:'Arcanian · Episódio I', title:'Devaneios', text:'Ikarius investiga uma morte marcada pela mesma espiral encontrada no caso de seu pai. Cada resposta amplia o crime até ele deixar de caber em uma única realidade.',
      physical:'Edição física', digital:'Edição Kindle', physicalMeta:'UICLAP · impressão sob demanda', digitalMeta:'Amazon · acesso digital',
      physicalTitle:'Para ler, guardar e voltar.', digitalTitle:'Para começar sem esperar o frete.',
      physicalText:'Edição em brochura produzida sob demanda. Pagamento, produção, prazo e envio são administrados pela UICLAP.', digitalText:'Edição digital disponível pela Amazon para Kindle e aplicativo em celular, tablet ou computador.',
      before:'Antes de comprar', notices:['O pagamento não acontece neste site.','Preço e disponibilidade podem mudar na plataforma.','Pedidos e entregas são atendidos pela loja escolhida.'],
      synopsis:'Sinopse', synopsisTitle:'O caso não começou com Ezequiel.',
      synopsisP1:'Após o assassinato do delegado Ezequiel Sant’Anna, Ikarius encontra uma espiral idêntica à marca ligada à morte de seu pai vinte anos antes.',
      synopsisP2:'Entre evidências anômalas, lembranças que não podem ser tratadas como prova e organizações em conflito, a investigação cresce para além de Bravara.',
      choose:'Escolha a edição', physicalButton:'Comprar físico', digitalButton:'Comprar Kindle', facts:['17 capítulos','Primeira edição · 2026','Físico e digital']
    },
    footer: { location:'Arcanian · Episódio I disponível', rights:'© 2026 Two Eyes On You™. Todos os direitos reservados.' },
    notFound: { title:'Esta página não existe.', button:'Voltar ao início' }
  },
  en: {
    nav: { home:'Home', projects:'Projects', news:'News', wiki:'Wiki', timeline:'Timeline', media:'Media', studio:'Studio', documents:'Documents', contact:'Contact', buy:'Buy Devaneios' },
    routes: { '/':'Home', '/arcanian':'Projects', '/wiki':'Arcanian Wiki', '/timeline':'Timeline', '/news':'News', '/media':'Media', '/about':'Studio', '/documentation':'Documents', '/contact':'Contact', '/purchase':'Buy Devaneios' },
    common: { explore:'Explore', learn:'Learn more', viewAll:'View all', readMore:'Read more', back:'Back', search:'Search', close:'Close', buy:'Buy', available:'Available', soon:'In development', external:'Opens on another platform', overview:'Overview', direction:'Direction', connections:'Connections', noResults:'No results found.', originalPt:'Editorial content is available in its original Portuguese version.' },
    settings: { title:'Site preferences', description:'Adjust language, visual identity, reading and accessibility. Your choices are saved in this browser.', theme:'Theme', language:'Language', studio:'Arcanian Atelier', night:'Nocturne Archive', light:'Gallery Edition', sand:'Editorial Codex', blue:'Analytical Terminal', open:'Appearance and language' },
    search: { title:'Quick search', placeholder:'Search for a project, news item, person or page', navigation:'Navigation', work:'Project', wiki:'Wiki', document:'Document' },
    home: { eyebrow:'Two Eyes On You Studios', title:'Stories to read, play and remember.', text:'The home of Devaneios, Menos Um, Tormenta and the Arcanian Game.', primary:'Explore our projects', secondary:'About the studio', featured:'Featured', latest:'Latest news', projects:'Studio projects', projectsText:'Each story chooses the format that serves it best. Arcanian connects books, comics and a game without turning them into the same experience.', studioTitle:'A story does not have to end where it began.', studioText:'Two Eyes On You was created to build projects that cross formats without losing authorship. We define the scene, characters and feeling first. Technology comes later.', studioButton:'Meet Two Eyes On You' },
    projects: { eyebrow:'Arcanian in different forms', title:'Projects', text:'Four works entering the same universe through different conflicts and points of view.', choose:'Choose a project', intro:'Arcanian is the studio’s main universe. Every title stands on its own while sharing consequences, characters and ideas.' },
    work: { themes:'Core ideas', related:'Explore on the wiki', wikiText:'Characters, places and concepts that provide context for this work.', wikiButton:'Open Arcanian Wiki' },
    wiki: { eyebrow:'Official encyclopedia', title:'Arcanian Wiki', text:'Characters, places, organizations, events and concepts from the universe.', categories:'Categories', all:'All', spoilers:'Show spoilers', protected:'Spoiler content', open:'Open entry', results:'entries', source:'Primary source: Arcanian: Devaneios', original:'Original Portuguese text', back:'Back to wiki', related:'Related entries', classification:'Category' },
    timeline: { eyebrow:'Arcanian universe', title:'Timeline', text:'An organized view of known events, with protection for major reveals.', show:'Show spoilers', hide:'Hide spoilers', locked:'Protected event', lockedText:'Enable spoilers to view this event.' },
    news: { eyebrow:'Two Eyes On You', title:'News', text:'Releases, production updates, events and changes across the studio’s projects.' },
    media: { eyebrow:'Studio gallery', title:'Media', text:'Images, videos, development art and public materials.', video:'Featured video', images:'Gallery' },
    studio: { eyebrow:'Two Eyes On You · since 2018', title:'Two Eyes On You', text:'The studio develops Arcanian through works that do not repeat the same story: Devaneios, Menos Um, Tormenta and the Game.', manifesto:'Our direction', manifestoTitle:'Every work needs its own reason to exist.', p1:'Devaneios uses investigation and Ikarius’s inner reasoning. Menos Um moves closer to Joel and Elisabeth. Tormenta turns the past into visual sequence. The Game gives part of those decisions to the player.', p2:'When a scene changes format, it must gain something: intimacy in prose, time between panels, action, cooperation or control.', areas:'What we do', process:'How we work', projects:'In production', processTitle:'Who is in the scene, what is at risk and which form can sustain it.', contact:'Partnerships, press and licensing', contactTitle:'Talk directly to the studio.' },
    docs: { eyebrow:'Institutional information', title:'Documents', text:'Policies, terms of use, licenses and brand guidelines.', summary:'Contents', updated:'Updated', legalOriginal:'The legally valid version of this document is available in Portuguese.' },
    contact: { eyebrow:'Official channel', title:'Talk to the team', text:'Support, press, partnerships, licensing and intellectual property.', button:'Send email', areas:['Support and technical issues','Partnerships and collaborations','Press and creators','Licensing and rights'] },
    purchase: { eyebrow:'Arcanian · Episode I', title:'Devaneios', text:'Ikarius investigates a death marked by the same spiral found in his father’s case. Each answer expands the crime until it no longer fits within a single reality.', physical:'Print edition', digital:'Kindle edition', physicalMeta:'UICLAP · print on demand', digitalMeta:'Amazon · digital access', physicalTitle:'To read, keep and return to.', digitalTitle:'To begin without waiting for shipping.', physicalText:'Print-on-demand paperback. Payment, production, delivery times and shipping are handled by UICLAP.', digitalText:'Digital edition available through Amazon for Kindle and the app on phone, tablet or computer.', before:'Before you buy', notices:['Payment does not take place on this website.','Price and availability may change on the platform.','Orders and delivery are handled by the selected store.'], synopsis:'Synopsis', synopsisTitle:'The case did not begin with Ezequiel.', synopsisP1:'After delegate Ezequiel Sant’Anna is murdered, Ikarius finds a spiral identical to the mark connected to his father’s death twenty years earlier.', synopsisP2:'Between anomalous evidence, memories that cannot be treated as proof and organizations in conflict, the investigation grows beyond Bravara.', choose:'Choose an edition', physicalButton:'Buy print edition', digitalButton:'Buy Kindle edition', facts:['17 chapters','First edition · 2026','Print and digital'] },
    footer: { location:'Arcanian · Episode I available', rights:'© 2026 Two Eyes On You™. All rights reserved.' },
    notFound: { title:'This page does not exist.', button:'Back to home' }
  },
  es: {
    nav: { home:'Inicio', projects:'Proyectos', news:'Noticias', wiki:'Wiki', timeline:'Cronología', media:'Medios', studio:'Estudio', documents:'Documentos', contact:'Contacto', buy:'Comprar Devaneios' },
    routes: { '/':'Inicio', '/arcanian':'Proyectos', '/wiki':'Wiki Arcanian', '/timeline':'Cronología', '/news':'Noticias', '/media':'Medios', '/about':'Estudio', '/documentation':'Documentos', '/contact':'Contacto', '/purchase':'Comprar Devaneios' },
    common: { explore:'Explorar', learn:'Saber más', viewAll:'Ver todo', readMore:'Leer más', back:'Volver', search:'Buscar', close:'Cerrar', buy:'Comprar', available:'Disponible', soon:'En desarrollo', external:'Se abre en otra plataforma', overview:'Resumen', direction:'Dirección', connections:'Conexiones', noResults:'No se encontraron resultados.', originalPt:'El contenido editorial está disponible en su versión original en portugués.' },
    settings: { title:'Preferencias del sitio', description:'Ajusta idioma, identidad visual, lectura y accesibilidad. Tus opciones se guardan en este navegador.', theme:'Tema', language:'Idioma', studio:'Atelier Arcanian', night:'Archivo Nocturno', light:'Edición Museográfica', sand:'Códice Editorial', blue:'Terminal Analítico', open:'Apariencia e idioma' },
    search: { title:'Búsqueda rápida', placeholder:'Busca un proyecto, noticia, persona o página', navigation:'Navegación', work:'Proyecto', wiki:'Wiki', document:'Documento' },
    home: { eyebrow:'Two Eyes On You Studios', title:'Historias para leer, jugar y recordar.', text:'Un estudio independiente brasileño que crea universos originales en literatura, juegos, cómics, imagen y sonido.', primary:'Conoce nuestros proyectos', secondary:'Sobre el estudio', featured:'Destacado', latest:'Últimas noticias', projects:'Proyectos del estudio', projectsText:'Cada obra elige el formato que mejor sirve a la historia. Arcanian conecta libros, cómics y un juego sin convertirlos en la misma experiencia.', studioTitle:'Una obra no tiene que terminar donde empezó.', studioText:'Two Eyes On You nació para crear proyectos que atraviesan formatos sin perder autoría. Primero definimos la escena, los personajes y la sensación. La tecnología viene después.', studioButton:'Conoce Two Eyes On You' },
    projects: { eyebrow:'Universos y obras', title:'Proyectos', text:'Literatura, cómics y juegos desarrollados bajo una misma dirección creativa.', choose:'Elige un proyecto', intro:'Arcanian es el universo principal del estudio. Cada título funciona por separado y comparte consecuencias, personajes e ideas.' },
    work: { themes:'Ideas centrales', related:'Explora en la wiki', wikiText:'Personajes, lugares y conceptos que ayudan a comprender mejor esta obra.', wikiButton:'Abrir Wiki Arcanian' },
    wiki: { eyebrow:'Enciclopedia oficial', title:'Wiki Arcanian', text:'Personajes, lugares, organizaciones, acontecimientos y conceptos del universo.', categories:'Categorías', all:'Todo', spoilers:'Mostrar spoilers', protected:'Contenido con spoiler', open:'Abrir entrada', results:'entradas', source:'Fuente principal: Arcanian: Devaneios', original:'Texto original en portugués', back:'Volver a la wiki', related:'Entradas relacionadas', classification:'Categoría' },
    timeline: { eyebrow:'Universo Arcanian', title:'Cronología', text:'Una visión organizada de los acontecimientos conocidos, con protección para revelaciones importantes.', show:'Mostrar spoilers', hide:'Ocultar spoilers', locked:'Evento protegido', lockedText:'Activa los spoilers para consultar este acontecimiento.' },
    news: { eyebrow:'Two Eyes On You', title:'Noticias', text:'Lanzamientos, producción, eventos y cambios en los proyectos del estudio.' },
    media: { eyebrow:'Galería del estudio', title:'Medios', text:'Imágenes, videos, arte de desarrollo y materiales públicos.', video:'Video destacado', images:'Galería' },
    studio: { eyebrow:'Two Eyes On You · desde 2018', title:'Two Eyes On You', text:'El estudio desarrolla Arcanian en obras que no repiten la misma historia: Devaneios, Menos Um, Tormenta y el Juego.', manifesto:'Nuestra dirección', manifestoTitle:'Cada obra necesita una razón propia para existir.', p1:'Two Eyes On You trabaja con literatura, juegos, cómics, arte y sonido como lenguajes distintos, no como versiones menores entre sí.', p2:'Un juego no debe parecer una simple adaptación y un libro no debe existir para anunciar otro producto. Cada proyecto debe justificar su formato.', areas:'Lo que hacemos', process:'Cómo trabajamos', projects:'En producción', processTitle:'Quién está en la escena, qué está en riesgo y qué forma puede sostenerlo.', contact:'Alianzas, prensa y licencias', contactTitle:'Habla directamente con el estudio.' },
    docs: { eyebrow:'Información institucional', title:'Documentos', text:'Políticas, términos de uso, licencias y directrices de marca.', summary:'Índice', updated:'Actualizado', legalOriginal:'La versión jurídicamente válida de este documento está disponible en portugués.' },
    contact: { eyebrow:'Canal oficial', title:'Habla con el equipo', text:'Soporte, prensa, alianzas, licencias y propiedad intelectual.', button:'Enviar correo', areas:['Soporte y fallos técnicos','Alianzas y colaboraciones','Prensa y creadores','Licencias y derechos'] },
    purchase: { eyebrow:'Arcanian · Episodio I', title:'Devaneios', text:'Ikarius investiga una muerte marcada por la misma espiral encontrada en el caso de su padre. Cada respuesta amplía el crimen hasta que deja de caber en una sola realidad.', physical:'Edición física', digital:'Edición Kindle', physicalMeta:'UICLAP · impresión bajo demanda', digitalMeta:'Amazon · acceso digital', physicalTitle:'Para leer, guardar y volver.', digitalTitle:'Para empezar sin esperar el envío.', physicalText:'Edición en rústica producida bajo demanda. UICLAP gestiona el pago, la producción, los plazos y el envío.', digitalText:'Edición digital disponible en Amazon para Kindle y la aplicación en móvil, tableta u ordenador.', before:'Antes de comprar', notices:['El pago no se realiza en este sitio.','El precio y la disponibilidad pueden cambiar en la plataforma.','Los pedidos y envíos son gestionados por la tienda elegida.'], synopsis:'Sinopsis', synopsisTitle:'El caso no comenzó con Ezequiel.', synopsisP1:'Tras el asesinato del delegado Ezequiel Sant’Anna, Ikarius encuentra una espiral idéntica a la marca relacionada con la muerte de su padre veinte años antes.', synopsisP2:'Entre pruebas anómalas, recuerdos que no pueden tratarse como evidencia y organizaciones en conflicto, la investigación crece más allá de Bravara.', choose:'Elige la edición', physicalButton:'Comprar físico', digitalButton:'Comprar Kindle', facts:['17 capítulos','Primera edición · 2026','Físico y digital'] },
    footer: { location:'Arcanian · Episódio I disponível', rights:'© 2026 Two Eyes On You™. Todos los derechos reservados.' },
    notFound: { title:'Esta página no existe.', button:'Volver al inicio' }
  },
  it: {
    nav: { home:'Home', projects:'Progetti', news:'Notizie', wiki:'Wiki', timeline:'Cronologia', media:'Media', studio:'Studio', documents:'Documenti', contact:'Contatti', buy:'Acquista Devaneios' },
    routes: { '/':'Home', '/arcanian':'Progetti', '/wiki':'Wiki Arcanian', '/timeline':'Cronologia', '/news':'Notizie', '/media':'Media', '/about':'Studio', '/documentation':'Documenti', '/contact':'Contatti', '/purchase':'Acquista Devaneios' },
    common: { explore:'Esplora', learn:'Scopri di più', viewAll:'Vedi tutto', readMore:'Leggi', back:'Indietro', search:'Cerca', close:'Chiudi', buy:'Acquista', available:'Disponibile', soon:'In sviluppo', external:'Si apre su un’altra piattaforma', overview:'Panoramica', direction:'Direzione', connections:'Connessioni', noResults:'Nessun risultato trovato.', originalPt:'Il contenuto editoriale è disponibile nella versione originale in portoghese.' },
    settings: { title:'Preferenze del sito', description:'Regola lingua, identità visiva, lettura e accessibilità. Le preferenze vengono salvate in questo browser.', theme:'Tema', language:'Lingua', studio:'Atelier Arcanian', night:'Archivio Notturno', light:'Edizione Museale', sand:'Codice Editoriale', blue:'Terminale Analitico', open:'Aspetto e lingua' },
    search: { title:'Ricerca rapida', placeholder:'Cerca un progetto, una notizia, una persona o una pagina', navigation:'Navigazione', work:'Progetto', wiki:'Wiki', document:'Documento' },
    home: { eyebrow:'Two Eyes On You Studios', title:'Storie da leggere, giocare e ricordare.', text:'Uno studio indipendente brasiliano che crea mondi originali attraverso letteratura, giochi, fumetti, immagini e suono.', primary:'Scopri i nostri progetti', secondary:'Chi siamo', featured:'In evidenza', latest:'Ultime notizie', projects:'Progetti dello studio', projectsText:'Ogni opera sceglie il formato più adatto alla storia. Arcanian collega libri, fumetti e un gioco senza renderli la stessa esperienza.', studioTitle:'Una storia non deve finire dove è iniziata.', studioText:'Two Eyes On You nasce per creare progetti che attraversano i formati senza perdere autorialità. Prima definiamo scena, personaggi e sensazione. La tecnologia viene dopo.', studioButton:'Scopri Two Eyes On You' },
    projects: { eyebrow:'Mondi e opere', title:'Progetti', text:'Letteratura, fumetti e giochi sviluppati sotto un’unica direzione creativa.', choose:'Scegli un progetto', intro:'Arcanian è l’universo principale dello studio. Ogni titolo è autonomo, ma condivide conseguenze, personaggi e idee.' },
    work: { themes:'Idee centrali', related:'Esplora nella wiki', wikiText:'Personaggi, luoghi e concetti che aiutano a comprendere meglio quest’opera.', wikiButton:'Apri Wiki Arcanian' },
    wiki: { eyebrow:'Enciclopedia ufficiale', title:'Wiki Arcanian', text:'Personaggi, luoghi, organizzazioni, eventi e concetti dell’universo.', categories:'Categorie', all:'Tutto', spoilers:'Mostra spoiler', protected:'Contenuto con spoiler', open:'Apri voce', results:'voci', source:'Fonte principale: Arcanian: Devaneios', original:'Testo originale in portoghese', back:'Torna alla wiki', related:'Voci correlate', classification:'Categoria' },
    timeline: { eyebrow:'Universo Arcanian', title:'Cronologia', text:'Una visione ordinata degli eventi noti, con protezione per le rivelazioni importanti.', show:'Mostra spoiler', hide:'Nascondi spoiler', locked:'Evento protetto', lockedText:'Attiva gli spoiler per consultare questo evento.' },
    news: { eyebrow:'Two Eyes On You', title:'Notizie', text:'Uscite, produzione, eventi e cambiamenti nei progetti dello studio.' },
    media: { eyebrow:'Galleria dello studio', title:'Media', text:'Immagini, video, concept art e materiali pubblici.', video:'Video in evidenza', images:'Galleria' },
    studio: { eyebrow:'Two Eyes On You · dal 2018', title:'Two Eyes On You', text:'Lo studio sviluppa Arcanian attraverso opere che non ripetono la stessa storia: Devaneios, Menos Um, Tormenta e il Gioco.', manifesto:'La nostra direzione', manifestoTitle:'Ogni opera ha bisogno di una ragione propria per esistere.', p1:'Two Eyes On You considera letteratura, giochi, fumetti, arte e suono linguaggi diversi, non versioni minori l’uno dell’altro.', p2:'Un gioco non deve sembrare un semplice adattamento e un libro non deve esistere per pubblicizzare un altro prodotto. Ogni progetto deve giustificare il proprio formato.', areas:'Cosa facciamo', process:'Come lavoriamo', projects:'In produzione', processTitle:'Chi è nella scena, cosa è in gioco e quale forma può sostenerlo.', contact:'Partnership, stampa e licenze', contactTitle:'Parla direttamente con lo studio.' },
    docs: { eyebrow:'Informazioni istituzionali', title:'Documenti', text:'Politiche, termini d’uso, licenze e linee guida del marchio.', summary:'Indice', updated:'Aggiornato', legalOriginal:'La versione giuridicamente valida di questo documento è disponibile in portoghese.' },
    contact: { eyebrow:'Canale ufficiale', title:'Parla con il team', text:'Supporto, stampa, partnership, licenze e proprietà intellettuale.', button:'Invia email', areas:['Supporto e problemi tecnici','Partnership e collaborazioni','Stampa e creator','Licenze e diritti'] },
    purchase: { eyebrow:'Arcanian · Episodio I', title:'Devaneios', text:'Ikarius indaga su una morte segnata dalla stessa spirale trovata nel caso di suo padre. Ogni risposta amplia il crimine finché non entra più in una sola realtà.', physical:'Edizione cartacea', digital:'Edizione Kindle', physicalMeta:'UICLAP · stampa su richiesta', digitalMeta:'Amazon · accesso digitale', physicalTitle:'Da leggere, conservare e riprendere.', digitalTitle:'Per iniziare senza attendere la spedizione.', physicalText:'Edizione tascabile stampata su richiesta. Pagamento, produzione, tempi e spedizione sono gestiti da UICLAP.', digitalText:'Edizione digitale disponibile su Amazon per Kindle e app su telefono, tablet o computer.', before:'Prima di acquistare', notices:['Il pagamento non avviene su questo sito.','Prezzo e disponibilità possono cambiare sulla piattaforma.','Ordini e consegne sono gestiti dal negozio scelto.'], synopsis:'Sinossi', synopsisTitle:'Il caso non è iniziato con Ezequiel.', synopsisP1:'Dopo l’omicidio del delegato Ezequiel Sant’Anna, Ikarius trova una spirale identica al marchio legato alla morte di suo padre vent’anni prima.', synopsisP2:'Tra prove anomale, ricordi che non possono essere trattati come prove e organizzazioni in conflitto, l’indagine cresce oltre Bravara.', choose:'Scegli l’edizione', physicalButton:'Acquista cartaceo', digitalButton:'Acquista Kindle', facts:['17 capitoli','Prima edizione · 2026','Cartaceo e digitale'] },
    footer: { location:'Arcanian · Episodio I disponibile', rights:'© 2026 Two Eyes On You™. Tutti i diritti riservati.' },
    notFound: { title:'Questa pagina non esiste.', button:'Torna alla home' }
  },
  ja: {
    nav: { home:'ホーム', projects:'プロジェクト', news:'ニュース', wiki:'Wiki', timeline:'年表', media:'メディア', studio:'スタジオ', documents:'ドキュメント', contact:'お問い合わせ', buy:'Devaneiosを購入' },
    routes: { '/':'ホーム', '/arcanian':'プロジェクト', '/wiki':'Arcanian Wiki', '/timeline':'年表', '/news':'ニュース', '/media':'メディア', '/about':'スタジオ', '/documentation':'ドキュメント', '/contact':'お問い合わせ', '/purchase':'Devaneiosを購入' },
    common: { explore:'見る', learn:'詳しく見る', viewAll:'すべて見る', readMore:'続きを読む', back:'戻る', search:'検索', close:'閉じる', buy:'購入', available:'発売中', soon:'開発中', external:'外部プラットフォームで開きます', overview:'概要', direction:'方向性', connections:'関連', noResults:'結果が見つかりません。', originalPt:'編集本文はポルトガル語の原文で提供されています。' },
    settings: { title:'サイト設定', description:'言語、視覚テーマ、読みやすさ、アクセシビリティを調整できます。設定はこのブラウザーに保存されます。', theme:'テーマ', language:'言語', studio:'Arcanian アトリエ', night:'夜間アーカイブ', light:'ギャラリー・エディション', sand:'編集コーデックス', blue:'分析ターミナル', open:'外観と言語' },
    search: { title:'クイック検索', placeholder:'作品、ニュース、人物、ページを検索', navigation:'ナビゲーション', work:'プロジェクト', wiki:'Wiki', document:'ドキュメント' },
    home: { eyebrow:'Two Eyes On You Studios', title:'読み、遊び、記憶に残る物語。', text:'文学、ゲーム、コミック、映像、音を通じて独自の世界をつくるブラジルのインディペンデントスタジオです。', primary:'プロジェクトを見る', secondary:'スタジオについて', featured:'注目作品', latest:'最新ニュース', projects:'スタジオのプロジェクト', projectsText:'物語ごとに最適な形式を選びます。Arcanianは書籍、コミック、ゲームをつなぎますが、同じ体験にはしません。', studioTitle:'物語は、始まった形式で終わる必要はありません。', studioText:'Two Eyes On Youは、作者性を失わずに複数の形式を横断する作品をつくるために生まれました。まず場面、人物、感情を定め、技術はその後に選びます。', studioButton:'Two Eyes On Youについて' },
    projects: { eyebrow:'世界と作品', title:'プロジェクト', text:'一つのクリエイティブディレクションのもとで制作される文学、コミック、ゲーム。', choose:'プロジェクトを選ぶ', intro:'Arcanianはスタジオの中心となる世界です。各作品は単独でも楽しめますが、結果、人物、テーマを共有しています。' },
    work: { themes:'作品の核', related:'Wikiで見る', wikiText:'作品をより深く理解するための人物、場所、概念。', wikiButton:'Arcanian Wikiを開く' },
    wiki: { eyebrow:'公式エンサイクロペディア', title:'Arcanian Wiki', text:'世界に登場する人物、場所、組織、出来事、概念をまとめています。', categories:'カテゴリー', all:'すべて', spoilers:'ネタバレを表示', protected:'ネタバレを含む内容', open:'項目を開く', results:'件', source:'主な出典：Arcanian: Devaneios', original:'ポルトガル語原文', back:'Wikiに戻る', related:'関連項目', classification:'カテゴリー' },
    timeline: { eyebrow:'Arcanianの世界', title:'年表', text:'判明している出来事を整理し、重要な展開にはネタバレ保護を設けています。', show:'ネタバレを表示', hide:'ネタバレを隠す', locked:'保護された出来事', lockedText:'この出来事を見るにはネタバレを有効にしてください。' },
    news: { eyebrow:'Two Eyes On You', title:'ニュース', text:'発売、制作、イベント、スタジオプロジェクトの更新情報。' },
    media: { eyebrow:'スタジオギャラリー', title:'メディア', text:'画像、映像、開発アート、公開素材。', video:'注目映像', images:'ギャラリー' },
    studio: { eyebrow:'Two Eyes On You · 2018—', title:'Two Eyes On You', text:'Devaneios、Menos Um、Tormenta、ゲームという異なる作品でArcanianを育てています。', manifesto:'私たちの方向性', manifestoTitle:'各作品には、その形で存在する理由が必要です。', p1:'Two Eyes On Youは文学、ゲーム、コミック、アート、音を、それぞれ異なる言語として扱います。どれかの縮小版ではありません。', p2:'ゲームは単なる映像化であるべきではなく、本は別の商品を宣伝するためだけに存在すべきではありません。形式には理由が必要です。', areas:'制作分野', process:'制作方法', projects:'制作中', processTitle:'誰が場面にいて、何が危険にさらされ、どの形式がそれを支えられるか。', contact:'提携・プレス・ライセンス', contactTitle:'スタジオへ直接お問い合わせください。' },
    docs: { eyebrow:'スタジオ情報', title:'ドキュメント', text:'ポリシー、利用規約、ライセンス、ブランドガイドライン。', summary:'目次', updated:'更新日', legalOriginal:'法的に有効な文書はポルトガル語版です。' },
    contact: { eyebrow:'公式窓口', title:'チームへのお問い合わせ', text:'サポート、プレス、提携、ライセンス、知的財産について。', button:'メールを送る', areas:['サポートと技術的な問題','提携とコラボレーション','プレスとクリエイター','ライセンスと権利'] },
    purchase: { eyebrow:'Arcanian · エピソードI', title:'Devaneios', text:'Ikariusは、父の事件と同じ螺旋が残された死を調査します。答えを得るたびに、犯罪は一つの現実に収まらない規模へ広がっていきます。', physical:'紙書籍', digital:'Kindle版', physicalMeta:'UICLAP · オンデマンド印刷', digitalMeta:'Amazon · デジタル', physicalTitle:'読み、手元に置き、何度も戻るために。', digitalTitle:'配送を待たずに読み始めるために。', physicalText:'オンデマンド印刷のペーパーバック版です。支払い、製造、納期、配送はUICLAPが管理します。', digitalText:'Amazonで購入できるデジタル版です。Kindle端末やスマートフォン、タブレット、PCのアプリで読めます。', before:'購入前に', notices:['このサイトでは決済を行いません。','価格と在庫は各プラットフォームで変更される場合があります。','注文と配送は選択したストアが対応します。'], synopsis:'あらすじ', synopsisTitle:'事件はEzequielから始まったのではない。', synopsisP1:'Ezequiel Sant’Annaの殺害後、Ikariusは20年前の父の死に関係するものと同じ螺旋を発見します。', synopsisP2:'異常な証拠、証明として扱えない記憶、対立する組織の間で、調査はBravaraを越えて広がります。', choose:'版を選ぶ', physicalButton:'紙書籍を購入', digitalButton:'Kindle版を購入', facts:['全17章','初版 · 2026年','紙・デジタル'] },
    footer: { location:'Arcanian · エピソードI発売中', rights:'© 2026 Two Eyes On You™. All rights reserved.' },
    notFound: { title:'このページは存在しません。', button:'ホームへ戻る' }
  }
};

export const workTranslations = {
  pt: {},
  en: {
    devaneios:{ eyebrow:'Novel · Episode I', summary:'An investigator trained to distrust easy answers encounters a case that repeats the mark left on his father’s murder.', long:'Arcanian begins as a criminal investigation and expands into anomalies, competing organizations and a dispute over the fate of entire realities.', themes:[['Method','Facts before conclusions. Every discovery must survive a test.'],['Scale','The case begins in a burned house and reaches a universe connected by ruptures.'],['Conflict','A family’s past becomes inseparable from the investigation.']], primary:'Choose an edition' },
    'menos-um':{ eyebrow:'Novel · Joel and Elisabeth', summary:'Joel and Elisabeth try to preserve something real in an age shaped by factories, poverty, violence and promises time does not respect.', long:'Menos Um brings the focus close to two people living inside events far larger than themselves, without turning love into an escape from the world.', themes:[['Relationship','Their bond is treated as a choice, not an idealization.'],['Period','Industrial cities, inequality and violence shape ordinary life.'],['Consequence','Time does not heal everything; some decisions only change the form of loss.']], primary:'Explore the work' },
    'a-ultima-danca':{ eyebrow:'Novel · Absolute Void · After Devaneios', summary:'After Devaneios, Ikarius, Joel and the Arnins face a violent outbreak, political decisions and a plan that pushes different peoples toward the same collapse.', long:'A Última Dança follows the consequences left open by Devaneios. A spreading crisis forces Ikarius to investigate beyond a single crime scene, while Joel confronts Elisabeth’s memory and the Arnins reach their final chance to prevent a wider collapse.', themes:[['After the investigation','Finding the truth does not remove the danger; it forces people and governments to act before they understand it.'],['Joel and Elisabeth','The dance in the title remains tied to their relationship and to the way Joel measures present choices against a lost future.'],['The Arnins’ last chance','The title also describes a final opportunity to break with structures that keep reproducing the same catastrophe.']], primary:'Explore the work' },
    tormenta:{ eyebrow:'Comic · Before the Great Day', summary:'Months before the Great Day, figures already regarded as legends face the events that prepared Arcanian’s rupture.', long:'Tormenta expands the past of the universe through comics, using composition, color and visual rhythm as part of the storytelling.', themes:[['Period','The story takes place months before the Great Day.'],['Cast','The focus is on names whose reputations were built before Devaneios.'],['Language','The narrative is designed for comics, not as an illustrated novel.']], primary:'Explore the work' },
    arcanian:{ title:'Arcanian', displayTitle:'Arcanian', eyebrow:'Arcanian game · Adaptation of the universe', summary:'A narrative action adventure that reorganizes stories from the universe into an experience for one or two players.', long:'The game adapts more than one book. Joel and Ikarius lead an experience that combines exploration, combat and scenes composed like moving artwork.', themes:[['Structure','Episodes connect different works without erasing their consequences.'],['Art','Character, line and color are defined before each scene is composed.'],['Play','The experience is designed for one or two players, with action and exploration.']], primary:'Explore the project' }
  },
  es: {
    devaneios:{ eyebrow:'Novela · Episodio I', summary:'Un investigador entrenado para desconfiar de respuestas fáciles encuentra un caso que repite la marca del asesinato de su padre.', long:'Arcanian empieza como una investigación criminal y crece hasta alcanzar anomalías, organizaciones enfrentadas y el destino de realidades enteras.', themes:[['Método','Hechos antes que conclusiones. Cada descubrimiento debe superar una prueba.'],['Escala','El caso parte de una casa incendiada y llega a un universo conectado por rupturas.'],['Conflicto','El pasado de una familia se vuelve inseparable de la investigación.']], primary:'Elegir edición' },
    'menos-um':{ eyebrow:'Novela · Joel y Elisabeth', summary:'Joel y Elisabeth intentan preservar algo verdadero en una época marcada por fábricas, pobreza, violencia y promesas que el tiempo no respeta.', long:'Menos Um acerca el foco a dos personas que viven dentro de acontecimientos mucho mayores sin convertir el amor en una fuga.', themes:[['Relación','Su vínculo se trata como una elección, no como una idealización.'],['Época','Las ciudades industriales, la desigualdad y la violencia moldean la vida cotidiana.'],['Consecuencia','El tiempo no cura todo; algunas decisiones solo cambian la forma de la pérdida.']], primary:'Conocer la obra' },
    'a-ultima-danca':{ eyebrow:'Novela · Vacío Absoluto · Después de Devaneios', summary:'Después de Devaneios, Ikarius, Joel y los Arnins enfrentan un brote violento, decisiones políticas y un plan que empuja a distintos pueblos hacia el mismo colapso.', long:'A Última Dança continúa las consecuencias abiertas por Devaneios. La crisis obliga a Ikarius a investigar más allá de una sola escena, mientras Joel enfrenta la memoria de Elisabeth y los Arnins llegan a su última oportunidad para impedir un colapso mayor.', themes:[['Después de la investigación','Descubrir la verdad no elimina el peligro; obliga a actuar antes de comprenderlo por completo.'],['Joel y Elisabeth','La danza del título sigue ligada a su relación y a la forma en que Joel mide el presente frente a un futuro perdido.'],['La última oportunidad de los Arnins','El título también describe la posibilidad final de romper con estructuras que repiten la catástrofe.']], primary:'Conocer la obra' },
    tormenta:{ eyebrow:'Cómic · Antes del Gran Día', summary:'Meses antes del Gran Día, figuras ya consideradas leyendas enfrentan los hechos que prepararon la ruptura de Arcanian.', long:'Tormenta amplía el pasado del universo en formato de cómic, usando composición, color y ritmo visual como parte del relato.', themes:[['Período','La historia sucede meses antes del Gran Día.'],['Elenco','El foco está en nombres cuya reputación precede a Devaneios.'],['Lenguaje','La narración está pensada para cómic, no como novela ilustrada.']], primary:'Conocer la obra' },
    arcanian:{ title:'Arcanian', displayTitle:'Arcanian', eyebrow:'Juego de Arcanian · Adaptación del universo', summary:'Una aventura narrativa de acción que reorganiza historias del universo en una experiencia para uno o dos jugadores.', long:'El juego adapta más de un libro. Joel e Ikarius protagonizan una experiencia que combina exploración, combate y escenas compuestas como arte en movimiento.', themes:[['Estructura','Los episodios conectan obras distintas sin borrar sus consecuencias.'],['Arte','Personajes, trazo y color se definen antes de componer cada escena.'],['Juego','La experiencia está pensada para una o dos personas, con acción y exploración.']], primary:'Conocer el proyecto' }
  },
  it: {
    devaneios:{ eyebrow:'Romanzo · Episodio I', summary:'Un investigatore abituato a diffidare delle risposte facili incontra un caso che ripete il segno lasciato nell’omicidio di suo padre.', long:'Arcanian inizia come indagine criminale e si espande verso anomalie, organizzazioni in conflitto e il destino di intere realtà.', themes:[['Metodo','Fatti prima delle conclusioni. Ogni scoperta deve superare una verifica.'],['Scala','Il caso parte da una casa incendiata e raggiunge un universo collegato da fratture.'],['Conflitto','Il passato di una famiglia diventa inseparabile dall’indagine.']], primary:'Scegli l’edizione' },
    'menos-um':{ eyebrow:'Romanzo · Joel ed Elisabeth', summary:'Joel ed Elisabeth cercano di preservare qualcosa di vero in un’epoca segnata da fabbriche, povertà, violenza e promesse che il tempo non rispetta.', long:'Menos Um porta lo sguardo vicino a due persone che vivono dentro eventi molto più grandi di loro, senza trasformare l’amore in una fuga.', themes:[['Relazione','Il loro legame è una scelta, non un’idealizzazione.'],['Epoca','Città industriali, disuguaglianza e violenza modellano la vita quotidiana.'],['Conseguenza','Il tempo non guarisce tutto; alcune decisioni cambiano solo la forma della perdita.']], primary:'Scopri l’opera' },
    'a-ultima-danca':{ eyebrow:'Romanzo · Vuoto Assoluto · Dopo Devaneios', summary:'Dopo Devaneios, Ikarius, Joel e gli Arnins affrontano un’epidemia violenta, decisioni politiche e un piano che spinge popoli diversi verso lo stesso collasso.', long:'A Última Dança prosegue le conseguenze lasciate aperte da Devaneios. La crisi costringe Ikarius a indagare oltre una singola scena, mentre Joel affronta il ricordo di Elisabeth e gli Arnins arrivano alla loro ultima possibilità di fermare un collasso più ampio.', themes:[['Dopo l’indagine','Scoprire la verità non elimina il pericolo; costringe ad agire prima di comprenderlo completamente.'],['Joel ed Elisabeth','La danza del titolo resta legata alla loro relazione e al modo in cui Joel misura il presente rispetto a un futuro perduto.'],['L’ultima possibilità degli Arnins','Il titolo descrive anche l’ultima occasione di spezzare strutture che continuano a riprodurre la catastrofe.']], primary:'Scopri l’opera' },
    tormenta:{ eyebrow:'Fumetto · Prima del Grande Giorno', summary:'Mesi prima del Grande Giorno, figure già considerate leggende affrontano gli eventi che prepararono la frattura di Arcanian.', long:'Tormenta amplia il passato dell’universo attraverso il fumetto, usando composizione, colore e ritmo visivo come parte della narrazione.', themes:[['Periodo','La storia si svolge mesi prima del Grande Giorno.'],['Personaggi','L’attenzione è su nomi la cui reputazione precede Devaneios.'],['Linguaggio','La narrazione è progettata per il fumetto, non come romanzo illustrato.']], primary:'Scopri l’opera' },
    arcanian:{ title:'Arcanian', displayTitle:'Arcanian', eyebrow:'Gioco di Arcanian · Adattamento dell’universo', summary:'Un’avventura narrativa d’azione che riorganizza le storie dell’universo in un’esperienza per uno o due giocatori.', long:'Il gioco adatta più di un libro. Joel e Ikarius guidano un’esperienza che unisce esplorazione, combattimento e scene composte come opere in movimento.', themes:[['Struttura','Gli episodi collegano opere diverse senza cancellarne le conseguenze.'],['Arte','Personaggi, segno e colore vengono definiti prima di comporre ogni scena.'],['Gioco','L’esperienza è pensata per uno o due giocatori, con azione ed esplorazione.']], primary:'Scopri il progetto' }
  },
  ja: {
    devaneios:{ eyebrow:'小説 · エピソードI', summary:'安易な答えを疑うよう訓練された捜査官が、父の殺害事件と同じ印を持つ事件に出会います。', long:'Arcanianは犯罪捜査として始まり、異常現象、対立する組織、複数の現実の運命へと広がっていきます。', themes:[['方法','結論より事実。発見は検証に耐えなければなりません。'],['規模','焼けた家から始まり、亀裂でつながる世界へ至ります。'],['対立','家族の過去と捜査を切り離せなくなります。']], primary:'版を選ぶ' },
    'menos-um':{ eyebrow:'小説 · JoelとElisabeth', summary:'工場、貧困、暴力、守られない約束に囲まれた時代に、JoelとElisabethは本物のものを守ろうとします。', long:'Menos Umは、より大きな出来事の中心にいる二人へ視点を近づけ、愛を現実からの逃避として描きません。', themes:[['関係','二人の絆は理想化ではなく選択として描かれます。'],['時代','工業都市、不平等、暴力が日常を形づくります。'],['結果','時間がすべてを癒すわけではありません。']], primary:'作品を見る' },
    'a-ultima-danca':{ eyebrow:'小説 · 絶対の虚無 · Devaneiosの後', summary:'Devaneiosの後、Ikarius、Joel、Arninsは、暴力的な感染、政治的判断、複数の民を同じ崩壊へ押し進める計画に直面します。', long:'A Última DançaはDevaneiosが残した結果を引き継ぎます。危機はIkariusに単独の事件を超えた捜査を迫り、JoelはElisabethの記憶と向き合い、Arninsはより大きな崩壊を止める最後の機会を迎えます。', themes:[['捜査の後','真実を知っても危険は消えず、完全に理解する前に行動を求められます。'],['JoelとElisabeth','題名のダンスは二人の関係と、失われた未来を基準にJoelが現在を選ぶ姿に結びつきます。'],['Arninsの最後の機会','題名は、同じ破局を繰り返す構造を断ち切る最後の可能性も意味します。']], primary:'作品を見る' },
    tormenta:{ eyebrow:'コミック · 「大いなる日」の前', summary:'「大いなる日」の数か月前、すでに伝説と呼ばれる人物たちがArcanianの亀裂を準備した出来事に向き合います。', long:'Tormentaはコミックとして世界の過去を広げ、構図、色、視覚的なリズムを物語そのものに使います。', themes:[['時期','物語は「大いなる日」の数か月前です。'],['登場人物','Devaneios以前から名を知られていた人物が中心です。'],['表現','挿絵付き小説ではなく、コミックとして設計されています。']], primary:'作品を見る' },
    arcanian:{ title:'Arcanian', displayTitle:'Arcanian', eyebrow:'Arcanian ゲーム · 世界の再構成', summary:'世界の複数の物語を、一人または二人で遊べるナラティブアクションアドベンチャーとして再構成します。', long:'ゲームは一冊だけを原作にしません。JoelとIkariusを中心に、探索、戦闘、動く絵画のような場面を組み合わせます。', themes:[['構成','エピソードが異なる作品を結び、結果を消しません。'],['アート','人物、線、色を決めてから場面を構成します。'],['ゲーム','一人または二人で遊べる探索とアクションです。']], primary:'プロジェクトを見る' }
  }
};

export const featuredWikiTranslations = {
  en: {
    ikarius:{ summary:'An investigator who separates every case into fact, inference and test before accepting an explanation.', body:['Ikarius works with anomalous cases in Bravara and treats the impossible as something that can be tested rather than an excuse for superstition.','His father Mountevoir’s death remains the one case he could never close.'] },
    aphride:{ summary:'Ikarius’s sister, an infiltration specialist and one of the few people able to interrupt his visions before they become decisions.', body:['Aphride crosses borders, identities and hostile structures with a discipline less rigid than her brother’s, but no less precise.','Their relationship combines provocation, protection and a shared memory of Mountevoir.'] },
    joel:{ summary:'A scientist whose attempt to cross time turns a personal decision into a rupture with consequences across realities.', body:['Joel’s work begins with a prototype capable of crossing time.','His relationship with Elisabeth is inseparable from the choice that changes the structure of reality.'] },
    elisabeth:{ summary:'Writer and central figure in Joel’s life, connected to the emotional origin of the temporal experiment.', body:['Elisabeth is not merely the reason for a decision; her life, work and relationship with Joel give that decision its human cost.'] },
    ciane:{ summary:'Center for the Investigation of Unspecified Anomalies, responsible for studying events that ordinary institutions cannot explain.', body:['C.I.A.N.E. organizes evidence, containment and field investigation without treating the anomalous as a spectacle.'] },
    bravara:{ summary:'Country where much of Devaneios takes place, including Paraícaba and the City of Wonders.', body:['Bravara combines coastal cities, industrial regions, mountain routes and public institutions that continue functioning beside anomalous events.'] },
    bayrule:{ summary:'Region tied to covert operations, political tension and movements that extend beyond Bravara.', body:['Bayrule appears as both a geographic and strategic space within the conflicts surrounding Arcanian.'] },
    devaneio:{ summary:'A vision or displacement that offers details too precise to be imagination and too contradictory to be treated as evidence.', body:['Ikarius records a devaneio without accepting it as fact. The concept defines one of the central tensions of the investigation.'] }
  },
  es: {
    ikarius:{ summary:'Investigador que separa cada caso en hecho, inferencia y prueba antes de aceptar una explicación.', body:['Ikarius trabaja con casos anómalos en Bravara y trata lo imposible como algo verificable, no como una excusa para la superstición.','La muerte de su padre, Mountevoir, sigue siendo el único caso que nunca pudo cerrar.'] },
    aphride:{ summary:'Hermana de Ikarius, especialista en infiltración y una de las pocas personas capaces de interrumpir sus visiones antes de que se conviertan en decisiones.', body:['Aphride cruza fronteras, identidades y estructuras hostiles con una disciplina menos rígida que la de su hermano, pero no menos precisa.'] },
    joel:{ summary:'Científico cuyo intento de atravesar el tiempo convierte una decisión personal en una ruptura con consecuencias entre realidades.', body:['El trabajo de Joel comienza con un prototipo capaz de cruzar el tiempo.','Su relación con Elisabeth es inseparable de la decisión que altera la estructura de la realidad.'] },
    elisabeth:{ summary:'Escritora y figura central en la vida de Joel, ligada al origen emocional del experimento temporal.', body:['Elisabeth no es solo el motivo de una decisión; su vida, su obra y su relación con Joel le dan un coste humano.'] },
    ciane:{ summary:'Centro de Investigación de Anomalías No Especificadas, responsable de estudiar hechos que las instituciones comunes no pueden explicar.', body:['El C.I.A.N.E. organiza pruebas, contención e investigación de campo sin tratar lo anómalo como espectáculo.'] },
    bravara:{ summary:'País donde transcurre gran parte de Devaneios, incluyendo Paraícaba y la Ciudad de las Maravillas.', body:['Bravara combina ciudades costeras, regiones industriales, rutas de montaña e instituciones que siguen funcionando junto a hechos anómalos.'] },
    bayrule:{ summary:'Región vinculada a operaciones encubiertas, tensión política y movimientos que se extienden más allá de Bravara.', body:['Bayrule es un espacio geográfico y estratégico dentro de los conflictos de Arcanian.'] },
    devaneio:{ summary:'Visión o desplazamiento con detalles demasiado precisos para ser imaginación y demasiado contradictorios para considerarse prueba.', body:['Ikarius registra un devaneio sin aceptarlo como hecho. El concepto define una tensión central de la investigación.'] }
  },
  it: {
    ikarius:{ summary:'Investigatore che divide ogni caso in fatto, inferenza e verifica prima di accettare una spiegazione.', body:['Ikarius lavora su casi anomali a Bravara e tratta l’impossibile come qualcosa da verificare, non come una scusa per la superstizione.','La morte di suo padre Mountevoir resta l’unico caso che non è mai riuscito a chiudere.'] },
    aphride:{ summary:'Sorella di Ikarius, specialista in infiltrazione e una delle poche persone capaci di interrompere le sue visioni prima che diventino decisioni.', body:['Aphride attraversa confini, identità e strutture ostili con una disciplina meno rigida di quella del fratello, ma non meno precisa.'] },
    joel:{ summary:'Scienziato il cui tentativo di attraversare il tempo trasforma una decisione personale in una frattura con conseguenze tra realtà.', body:['Il lavoro di Joel inizia con un prototipo capace di attraversare il tempo.','Il suo rapporto con Elisabeth è inseparabile dalla scelta che altera la struttura della realtà.'] },
    elisabeth:{ summary:'Scrittrice e figura centrale nella vita di Joel, legata all’origine emotiva dell’esperimento temporale.', body:['Elisabeth non è soltanto la ragione di una decisione; la sua vita e il rapporto con Joel ne mostrano il costo umano.'] },
    ciane:{ summary:'Centro per l’Indagine delle Anomalie Non Specificate, incaricato di studiare eventi che le istituzioni comuni non possono spiegare.', body:['Il C.I.A.N.E. organizza prove, contenimento e indagini sul campo senza trasformare l’anomalo in spettacolo.'] },
    bravara:{ summary:'Paese in cui si svolge gran parte di Devaneios, tra Paraícaba e la Città delle Meraviglie.', body:['Bravara unisce città costiere, regioni industriali, strade di montagna e istituzioni che continuano a funzionare accanto agli eventi anomali.'] },
    bayrule:{ summary:'Regione legata a operazioni segrete, tensioni politiche e movimenti che superano i confini di Bravara.', body:['Bayrule è uno spazio geografico e strategico nei conflitti di Arcanian.'] },
    devaneio:{ summary:'Visione o spostamento con dettagli troppo precisi per essere immaginazione e troppo contraddittori per diventare prova.', body:['Ikarius registra un devaneio senza accettarlo come fatto. Il concetto definisce una tensione centrale dell’indagine.'] }
  },
  ja: {
    ikarius:{ summary:'説明を受け入れる前に、事件を「事実・推論・検証」に分ける捜査官。', body:['IkariusはBravaraで異常事件を扱い、不可能なものを迷信ではなく検証可能な問題として扱います。','父Mountevoirの死は、彼が終わらせられなかった唯一の事件です。'] },
    aphride:{ summary:'Ikariusの姉妹で潜入の専門家。彼の幻視が判断に変わる前に止められる数少ない人物です。', body:['Aphrideは国境、身分、敵対的な組織を、兄とは異なる柔軟さと同じ精度で越えていきます。'] },
    joel:{ summary:'時間を越えようとした試みが、個人的な決断を複数の現実に影響する亀裂へ変えた科学者。', body:['Joelの研究は時間を越える試作機から始まります。','Elisabethとの関係は、現実の構造を変える選択と切り離せません。'] },
    elisabeth:{ summary:'作家でありJoelの人生の中心人物。時間実験の感情的な起点につながっています。', body:['Elisabethは単なる動機ではありません。彼女の人生とJoelとの関係が、その決断の人間的な代償を示します。'] },
    ciane:{ summary:'通常の組織では説明できない出来事を調査する「未特定異常現象調査センター」。', body:['C.I.A.N.E.は異常を見世物にせず、証拠、封じ込め、現場捜査を体系化します。'] },
    bravara:{ summary:'Paraícabaや「驚異の街」を含む、Devaneiosの主要な舞台となる国。', body:['Bravaraでは沿岸都市、工業地域、山岳道路、公共機関が異常現象の隣で機能し続けています。'] },
    bayrule:{ summary:'秘密作戦、政治的緊張、Bravaraを越える動きに関係する地域。', body:['BayruleはArcanianの対立における地理的・戦略的な空間です。'] },
    devaneio:{ summary:'想像にしては精密すぎ、証拠として扱うには矛盾しすぎる幻視や移動。', body:['Ikariusはdevaneioを事実として受け入れず記録します。この概念は捜査の中心的な緊張を形づくります。'] }
  }
};

export function getDictionary(lang) {
  return dictionaries[lang] || dictionaries.pt;
}

export function getByPath(object, path) {
  return path.split('.').reduce((value, key) => value?.[key], object);
}

export function localizedWork(work, lang) {
  if (lang === 'pt') return work;
  const translated = workContentTranslations[lang]?.[work.slug] || workTranslations[lang]?.[work.slug];
  if (!translated) return work;
  const primaryLabel = typeof translated.primary === 'string' ? translated.primary : translated.primary?.label;
  return {
    ...work,
    ...translated,
    title: translated.title || work.title,
    displayTitle: translated.displayTitle || translated.title || work.displayTitle,
    primary: { ...work.primary, ...(typeof translated.primary === 'object' ? translated.primary : {}), label: primaryLabel || work.primary?.label }
  };
}

export function localizedWikiEntry(entry, lang) {
  if (lang === 'pt') return { ...entry, translated: true };
  const translated = featuredWikiTranslations[lang]?.[entry.slug];
  const base = createLocalizedWikiEntry(entry, lang);
  return translated ? { ...base, ...translated, meta:base.meta, translated:true } : base;
}

export const newsTranslations = {
  en: [
    { category:'RELEASE', title:'Arcanian: Devaneios is officially available', text:'The first published work by Two Eyes On You is available in print and digital editions.' },
    { category:'ARCANIAN', title:'The Arcanian Wiki is now open', text:'Characters, locations, organizations and concepts from the universe are now organized in one place.' },
    { category:'GAME', title:'Characters first. Then the scene.', text:'The game’s art direction begins with cast, line and color before the environment is composed.' }
  ],
  es: [
    { category:'LANZAMIENTO', title:'Arcanian: Devaneios ya está disponible', text:'La primera obra publicada por Two Eyes On You puede adquirirse en edición física y digital.' },
    { category:'ARCANIAN', title:'La Wiki Arcanian ya está abierta', text:'Personajes, lugares, organizaciones y conceptos del universo reunidos en un solo espacio.' },
    { category:'JUEGO', title:'Primero los personajes. Después, la escena.', text:'La dirección artística del juego parte del elenco, el trazo y el color antes de componer cada ambiente.' }
  ],
  it: [
    { category:'USCITA', title:'Arcanian: Devaneios è ufficialmente disponibile', text:'La prima opera pubblicata da Two Eyes On You è disponibile in edizione cartacea e digitale.' },
    { category:'ARCANIAN', title:'La Wiki Arcanian è online', text:'Personaggi, luoghi, organizzazioni e concetti dell’universo sono raccolti in un unico spazio.' },
    { category:'GIOCO', title:'Prima i personaggi. Poi la scena.', text:'La direzione artistica del gioco parte da cast, segno e colore prima della composizione dell’ambiente.' }
  ],
  ja: [
    { category:'発売', title:'Arcanian: Devaneios 発売中', text:'Two Eyes On You初の出版作品を、紙書籍とデジタル版で購入できます。' },
    { category:'ARCANIAN', title:'Arcanian Wikiを公開しました', text:'世界の人物、場所、組織、概念を一つの場所にまとめました。' },
    { category:'ゲーム', title:'まず人物。その後に場面。', text:'ゲームのアートディレクションは、環境より先に登場人物、線、色を定めます。' }
  ]
};

export function localizedNews(items, lang) {
  const translated = newsTranslations[lang];
  if (!translated) return items;
  return items.map((item, index) => ({ ...item, ...(translated[index] || {}) }));
}
